petalinux-features.conf: Enable pni-names distro feature
Booting Zynq-7000 and Microblaze images on HW or QEMU user you can
observe below error message.

Error: argument "/en*" is wrong: "dev" not a valid ifname
Starting syslogd/klogd: done

Poky (Yocto Project Reference Distro) 5.0.2 zc702-zynq7 ttyPS0

zc702-zynq7 login:

This is due to pni-names distro feature is not enabled by default and
eudev uses classic network interface naming scheme. To resolve this
issue enable pni-names distro feature for Zynq-7000 and Microblaze
devices.

Signed-off-by: Sandeep Gundlupet Raju <sandeep.gundlupet-raju@amd.com>
Signed-off-by: Mark Hatle <mark.hatle@amd.com>